### ISSUE TITLE
Failure testing index.html

### ISSUE THREAD

**Issue by johnmarkos** [tempusjs/tempus#31]
Once I get past the jshint errors, when I run npm test, I get the following error. This stack trace is not very informative, but I'll dig a little and see if I can find out more.

```
Running "qunit:index" (qunit) task
Verifying property qunit.index exists in config...OK

Testing index.html

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by johnmarkos** [comment]
This project does not seem to be actively maintained, so I'm closing the issue.
